version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: 'git.victorphan.net'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://git.victorphan.net'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        nginx['client_max_body_size'] = '5120m'
        gitlab_workhorse['upload_max_size'] = '5120m'
    ports:
      - '80:80'
      - '443:443'
      - '2224:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
