version: '3.8'

services:
  # MySQL Database cho WordPress
  db:
    image: mysql:8.0
    container_name: wordpress_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password # Thay thế bằng mật khẩu gốc mạnh
      MYSQL_DATABASE: wordpress_db                # Tên database cho WordPress
      MYSQL_USER: wordpress_user                  # User cho WordPress
      MYSQL_PASSWORD: wordpress_password          # Mật khẩu cho WordPress user
    volumes:
      - ./db_data:/var/lib/mysql # Lưu trữ dữ liệu MySQL
    networks:
      - app-network

  # PHP-FPM Processor cho WordPress
  php-fpm:
    depends_on:
      - db
    image: wordpress:fpm # Sử dụng phiên bản FPM của WordPress image
    container_name: wordpress_php_fpm
    restart: always
    volumes:
      - ./wordpress_files:/var/www/html # Chia sẻ cùng volume với WordPress core
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    networks:
      - app-network

  # WordPress Core (Apache/Nginx mặc định bên trong image này)
  wordpress:
    depends_on:
      - db
      - php-fpm
    image: wordpress:latest
    container_name: wordpress_app
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./wordpress_files:/var/www/html # Chia sẻ cùng volume với php-fpm
    networks:
      - app-network
    # ***** THAY ĐỔI QUAN TRỌNG: PHƠI BÀY CỔNG RA HOST *****
    # Cổng 8080 trên Docker Host sẽ trỏ đến cổng 80 của container WordPress.
    # Bạn có thể chọn cổng khác ngoài 8080 nếu nó đã được sử dụng.
    ports:
      - "8080:80" 

networks:
  app-network:
    driver: bridge
